services:
  currency-frontend:
    image: midr/true-currency-frontend:staging
    ports:
      - "5001:80"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    tty: true
    depends_on:
      - currency-api
  
  currency-api:
    image: midr/true-currency-api:staging
    entrypoint: ["dotnet", "api.dll"]
    ports:
      - "5002:8080"
    depends_on:
      - mariadb
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: currencies
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --debug --http-api-update
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=mytoken
      - WATCHTOWER_LABEL_ENABLE=true
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - 8080:8080
  
  featurehub:
    image: featurehub/party-server:latest
    restart: always
    volumes:
      - featurehub-h2-data:/db
    ports: 
      - 8085:8085

volumes:
  mariadb:
  featurehub-h2-data: 